meta:
  schema_version: '1.0'
  project: AWLA
  units: hours
  periods:
  - P1
  - P2
  - P3
  notes: Global defaults for Academic Workload Allocation. Instance YAMLs may override
    any key.
weights:
  doc: Weights for soft constraints (higher = stronger).
  fairness_L1: 10
  pref: 1
  team_balance: 2
  split: 5
  stability: 3
  grade_guardrail: 0
  cross_campus: 0
  unavailability_near_hard: 10000
  near_hard: 100000000.0
  soft_conflicts: 1.0
fairness:
  doc: Fairness objective controls. Lexicographic=True prioritises fairness before
    other soft terms.
  metric: L1
  normalize_by: fte
  lexicographic: true
  epsilon: 0.01
  acceptable_band:
  - 0.9
  - 1.1
wam_adapter:
  doc: Base targets per contract (per 1.0 FTE). Instance config should set these;
    defaults are placeholders.
  default_target_hours:
    TR: 40.0
    TS: 60.0
  buyout_adjustments: []
  preallocations_mode: credit
solver:
  doc: Solver settings for ILP seed and Hyper-Heuristic (LAHC/LNS).
  method: matheuristic
  backend: highs            # optional fallback default
  threads: auto
  ilp:
    backend: highs          # <-- THIS is the one the code reads first
    threads: auto
  ilp_time_sec: 300
  ilp_mip_gap: 0.0
  hh_time_sec: 1200
  seed: 42
  acceptor: lahc
  lahc_length: 2000
  neighbourhood:
    operators: [reassign, swap, block_move, split_merge]
    block_move_size: 3
    reassign_bias_topk_percent: 20
  repair:
    enable: true
    mini_ilp_time_sec: 20
    mini_ilp_topk_modules: 5
  lexi:
    epsilon_fair: 0.01
checker:
  doc: Evaluation/validation policy.
  availability_zero_is_hard: true
  baseline_stability_include_only_eligible: true
  max_split_modules_warn: 9999
reports:
  doc: Reporting thresholds and toggles.
  band_green:
  - 0.95
  - 1.05
  band_amber:
  - 0.9
  - 1.1
  outlier_abs_hours: 10
  emit_excel: true
  emit_csv: true
  emit_json: true
logging:
  doc: Run metadata & artefacts to save.
  run_id_prefix: awla_run
  log_level: INFO
  save_assignment_csv: true
  save_violations_csv: true
  save_objective_breakdown_json: true
